/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "APP.h"
#include "stm32f10x_flash.h"








void delay()
{
  uint32_t i = 0;
  for(i = 0; i< 5000000;i++)
  {

  }

}


int main(void)
{

//     /* sequence of flash */
//    FLASH_UnlockBank1();
//    /* Clear All pending flags */
//    FLASH_ClearFlag(FLASH_FLAG_EOP | FLASH_FLAG_PGERR | FLASH_FLAG_WRPRTERR);
//   /* Define the number of page to be erased */
//    FLASH_ErasePage((uint32_t)0x08003000);
//    FLASH_ProgramOptionByteData((uint32_t)0x08003000, (uint8_t)0x01);
//    FLASH_LockBank1();


    app_init();
    if(!sw1)
    {
        jump_To_Boot();
    }
    else
    {
        Jump_To_App();
    }
}





